
# ==============================================================
# = Parametri Sicurezza AWS DynamoDb 
# ==============================================================
security:
  KEY : 
  SECRET : 
  
  # ==============================================================
# = Nome Bucket AWS S3 in uso
# ==============================================================    
buckets:
    product: 
    backup: 
